music/urls.py
from django.conf.urls import url

from . import views
app_name = 'music' #for namespacing url, which prevent conflicts between two url of different app with same name
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$',views.details, name='detail')
]

mysiteDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse
from . import mainViews
urlpatterns = [
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^$', mainViews.index, name='index'),
]

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
	artist      = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre       = models.CharField(max_length=100)
	album_logo  = models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)

	def __str__(self):
		return self.song_title

music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Album


def index(request):
    all_albums = Album.objects.all()
    # template = loader.get_template('music/indexx.html')
    context = {
        'all_albums': all_albums
    }

    return render (request, 'music/index.html', context)
    # return HttpResponse(template.render(context, request))


def details(request, album_id):
    # try:
    #   album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #   raise Http404("Album Nahi Mila Bhai!")
    # or we can use this
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/details.html', {'album': album})

music/templates/music/details.html
<!DOCTYPE html>
<html>
<head>
	<title>Details Page</title>
</head>
<body>
	<img src="{{ album.album_logo }}">
	<h1> {{ album.album_title }} </h1>
	<h3> {{ album.artist }} </h3>

	<ul>
		{% for songs in album.song_set.all %}
			<li> {{ songs.song_title }} - {{ songs.file_type }} </li>
		{% endfor %}
	</ul>
</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Django Bango</title>
</head>
<body>
	{% if all_albums %}
	<h3>Here goes all the songs</h3>
	<ul>
		{% for album in all_albums %}
			<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<h2>Nope! nothing found!</h2>
	{% endif %}
</body>
</html>